---
name: "Build Bioc Containers with TinyTex"

on:
  push:
    branches:
      - docker-builder
  schedule:
  # should run at midnight on the 1st and 15th days of each month
    - cron:  '0 0 1,15 * *'
  workflow_dispatch:


jobs:
  build-containers:
    name: Build ${{ matrix.config.platform }} Container
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
        - { platform: linux/arm64, tag: devel-arm64 }
        - { platform: linux/amd64, tag: devel-amd64 }

    steps: 
    
    - uses: actions/checkout@v4
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: ${{ matrix.config.platform }}
        push: true
        tags: ghcr.io/${{ github.actor }}/bioc-with-tinytex:${{ matrix.config.tag }}
